substitutions:
  _IMAGE: 'us-west2-docker.pkg.dev/${PROJECT_ID}/run/imgproxy'
  _REGION: 'us-west2'
options:
  dynamic_substitutions: true
  substitutionOption: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY


steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull $_IMAGE:latest || exit 0' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args: [
      'build',
      '--tag', '${_IMAGE}:${SHORT_SHA}',
      '--tag', '${_IMAGE}:latest',
      '--platform', 'linux/amd64',
      '-f', 'docker/Dockerfile',
      '.'
    ]
    waitFor: [ "-" ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to latest tag'
    args: [
      'push',
      '${_IMAGE}:latest',
    ]
    waitFor:
      - 'Build image'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push to hash tag'
    args: [
      'push',
      '${_IMAGE}:${SHORT_SHA}',
    ]
    waitFor:
      - 'Build image'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    waitFor:
      - 'Push to hash tag'
    args: [
      'run', 'deploy', 'imgproxy', '--image', '${_IMAGE}:${SHORT_SHA}',
      '--platform', 'managed', '--region', '$_REGION', '--project', '$PROJECT_ID',
    ]

images:
  - '$_IMAGE:$SHORT_SHA'
  - '$_IMAGE:latest'
